version: 2
updates:
  # Enable version updates for root dependencies
  - package-ecosystem: "npm"
    directories: # Location of package.json file
      - "/"
      - "/packages/*"
      - "/packages/vscode-messenger-devtools/webview-ui"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-type: "development"
